### ISSUE TITLE
Crash when saving

### ISSUE THREAD

**Issue by barefootcoder** [skoneka/screen-session#13]
Just installed `screen-session`.  `scs dump` seems to work fine, but save gives me a crash:

```
[tyr:~] scs save base

Creating directories:
Setting up session directory "base__tmp"

Saving layouts:
No layouts to save.

Saving windows:
Traceback (most recent call last):
  File "/usr/local/share/screen-session/screen_saver.py", line 305, in main
    ret = scs.save()
  File "/usr/local/share/screen-session/ScreenSaver.py", line 121, in save
    self.__save_screen()
  File "/usr/local/share/screen-session/ScreenSaver.py", line 883, in __save_screen
    cpids = sc.get_tty_pids(ctty)
  File "/usr/local/share/screen-session/GNUScreen.py", line 532, in _get_tty_pids_ps_with_cache_find
    return tty_and_pids[int(ctty.rsplit('/', 1)[1])]
KeyError: 8                                       
session saving totally failed                      
0 basic; 4 basic; 6 basic; 34 basic; 33 basic; 32 basic; 31 basic; 30 basic; 29 basic; 28 basic; 27 basic; 26 basic; 25  basic; (vim)24 basic; (vim)23 basic; 22 basic; 21 basic; 20 basic; 19 basic; 18 basic; 17 basic; 16 basic; (vim)15 basic; 14 basic; 13 basic; 12 basic; 11 basic; 10 basic; 9 basic; 8 basic; 7 basic; [tyr:~]
[tyr:~] scs --version                
screen-session 0.6.4 - a collection of tools for GNU Screen.
[tyr:~] screen --version                    
Screen version 4.01.00scs_0.6.4 (screen-session project) 27-August-11
```

Any thoughts?

**Comment by skoneka** [comment]
Thanks for the bug report. This commit should fix the crash:
skoneka@fe619cd
Can you try the latest git sources?
https://github.com/skoneka/screen-session/tarball/master

**Comment by barefootcoder** [comment]
Okay, that does indeed fix the crash, but I note there are a few "errors during window saving":

```
[tyr:~] scs save base

Creating directories:
Setting up session directory "base__tmp"

Saving layouts:
No layouts to save.

Saving windows:
0 basic; 6 basic; (vim)1 basic; (vim)9 basic; (vim)15 basic; 34 basic; (vim)27 basic; 16 basic; 3 basic; 5 basic; (vim)4 basic; (vim)23 basic; (vim)24 basic; (vim)2 basic; 33 basic; 32 basic; 31 basic; 30 basic; 29 basic; 28 basic; 26 basic; 25  basic; 22 basic; 21 basic; 20 basic; 19 basic; 18 basic; 17 basic; 14 basic; 13 basic; 12 basic; 11 basic; 10 basic; 8       basic; 7 basic;
Errors during windows saving:
0 PID 21894: Unable to access ( [Errno 2] No such file or directory: '/proc/21894/cwd' )
5 Unable to access /dev/pts/8 ( 8 )
33 PID 5630: Unable to access ( [Errno 13] Permission denied: '/proc/5630/cwd' )
10 PID 4582: Unable to access ( [Errno 13] Permission denied: '/proc/4582/cwd' )

Saved: 13:43:27 Oct 24 d-smo-bburden 0.16 0.56 0.39

Cleaning up scrollbacks.                      
Waiting for vim savefiles... done         
compressing...                       
session "4357.base"
saved as "base"                             
```

I'm guessing these are the result of trying to get the pwd for windows that happen to be `su`ed to root.  Not sure about the unable to access error on the term.  Can you help me understand the errors a bit better so I can see where the problem areas are?  Like, is the integer in front of the error the window number?  If so, I can understand the "5" one, but I don't get the "0" one at all ...

Any light you could shed would be helpful.

**Comment by skoneka** [comment]
**0 PID 21894: Unable to access ( [Errno 2] No such file or directory: '/proc/21894/cwd' )**
If you are on Linux, it indicates than session saver found this process in _"ps -U $USER -o tty,pid,ppid"_ output, but it wasn't existing any longer after we started scanning /proc. Probably, screen-session was running in this window and PID 21894 was the _"ps"_ command itself. Running _"scs dump ."_ also causes a similar error.

**5 Unable to access /dev/pts/8 ( 8 )**
You are right, it happens after starting a new window with _":screen su"_ (not handling this error also caused the crash).

**33 PID 5630: Unable to access ( [Errno 13] Permission denied: '/proc/5630/cwd' )
10 PID 4582: Unable to access ( [Errno 13] Permission denied: '/proc/4582/cwd' )**
Looks like some SUID processes in those windows (screen, su, etc.). At the moment, screen-session is not capable of saving other user's processes. But I plan to circumvent it with optionally SUID get-pid-info program.

I hope it explains a bit. Please don't hesitate if you have any further questions.

**Comment by barefootcoder** [comment]
Okay, so I should figure that I'll have to restore my su/sudo windows by hand, and that first error is completely ignorable.  Well, it looks like my Fedora update wants me to reboot (again), so I reckon I'll do that tomorrow and we'll see how well it works picking everything back up. :-)

Thanx for the help.
