### ISSUE TITLE
regionsize not implemented??

### ISSUE THREAD

**Issue by vituko** [skoneka/screen-session#2]
-X: unknown command 'regionsize'

In the INSTALL file you say :
gnu_screen.diff changes:
- add "tty" command
- add "regionsize" command
- make "group" queryable
- associate focuminsize with the layout

...but no reference to regionsize anymore

so forgotten some patches, maybe?

The program really seems great, but not tested yet ;)

**Comment by vituko** [comment]
Well, this happened with the head of the git repository. The 0.60 tag works, still I've got some errors (maybe not understood behavior):
.Example when last_win is out of --maxwin
.When a window just had a tail -f x, when reloaded, if tail is killed, then its shell ends too
.The regions in a layout get dettached from their original windows (only sometimes).
.The shell history of each window get mixed, tried with bash, maybe in zsh it takes care  about that, maybe just keeping a hist file for some windows could do the trick..

But anyway it seems to be in an usable state.
Its specially usefull with vim, I miss recording viminfo and undo history (7.3), but as it is, it's great (maybe just a couple lines needed in __save_vim).

So, a really great app, thanks.

**Comment by skoneka** [comment]
Thats right, I forgot about the patch. Thanks!
Didn't know about viminfo and the possibility to save undo history. 
I use a global shell history, so I didn't notice the issue with mixed shell histories.
The problem with windows detached from their regions is already solved in git. I don't understand the problem with "tail -f file" and last_win. Could you explain it?

**Comment by vituko** [comment]
Ok, if a window is executing tail -f when saving the session, then after restoring, if you pres CTRL+C to end this app, the window shell also exits. It's strange, I dont know what happens.

If I remember well, last_win records the current window when saving. The current window is usually where you execute the screen-session save command and its easly expressly opened just for that purpose and then it becomes the last window. So if I want to exclude this window with --maxwin, when restoring I get a (non fatal) error. So I suppose that in this case it should be checked that, cause the current window is not saved, the current one could become the first or last, for example.

The vim permanent undo history is new in last version, 7.3 (already in Debian Sid), it was a patch for a while and a very expected feature for me.

Well, as Bash doesnt share the history among its shells, its the default behavior, I tested Zsh for a while and I liked it (I like having the vi mode and seeing when in insert or command mode), but... there are some little differences that made me crazy, so I switched back to Bash, one day Ill try again. So, an interesting possibility is to get a different history file in a shell when needed, maybe something like screen-session fork-hist and merge-hist, or just searching the env var that holds the path and saving it associated with this window, just suggestions...

So, thanks for your answer and again for this cool app.

**Comment by skoneka** [comment]
Thank you for your time and great ideas.

screen-session restores programs running: shell -c "program; shell"
^C will stop 'bash -c "tail ; bash"' altogether (or any other program which does not catch ^C). I haven't noticed it earlier and don't know how to fix it. As a workaround you can use kill tool included with screen-session. Running ":exec scs kill" will send SIGTERM to last process started in this window.
BTW, if windows disappear mysteriously try :zombie command.

I didin't anticipate using --maxwin for excluding windows. Probably I should add --exclude [windows] option and remove --maxwin altogether after adding ":maxwin max" to Screen which will return current biggest window number (or better dump all window numbers).

:wundo seems promising, but I am no vim expert. People on #vim told me to try :bufdo exec 'wundo! /tmp/'.expand('%').'.undo'
but it doesn't work properly. As soon as I figure it out I will include undo saving.

Saving shell history would probably require some hack in user's rc file and reading env vars. Furthermore, it has to work on linux, freebsd and solaris before I can release it. A lot of trouble (for a feature which I don't use).

**Comment by vituko** [comment]
Ok, I didnt understood what --maxwin was for.
About the shell history, it was just an idea, in fact its not implemented in shells so... maybe if I had time enough...

And starting from signals, I ended trying to test shells and processes and well, there are some more ideas :

I realized that the env vars are lost :(
Chained commands are partially (command1 && command2 ->  command1 or command1 | command2 -> command2) or fully lost (command1 ; command2)
If a window has a background process, it get reloaded in foreground, if there are more than one background process, then the arguments get mixed and only the first one executes correctly.
Subshell hierarchies seem to not being considered : just the first shell will be recovered and emtpy, a particular case could be switching the user (su).

So, I suppose that it can be too hard to consider so many possibilities, maybe impossible to recover some complex structures, and it can be up to a particular program, imagine that Im editing in vim from the stdin (a pipe), the best choice could be to repeat the command and pipe again to vim, maybe could be to write a temporary file... but anyway it should be well documented which kind of processes schemas could be saved and which not, because it can be dangerous and lead to data lose, maybe it should be warned when saving that some windows would lose information.

Just some more suggestions, its really not an easy task to save a screen session ;)

**Comment by vituko** [comment]
Mmm Ive seen youve already commited changes, but Im still with 0.60, so...

**Comment by skoneka** [comment]
Yes, the current program recovery scheme is completely dumb and definitely requires more work (but still, it is good enough for 90% of my use cases). screen-session is much better at recovering a structure of tens of windows nested in groups and layouts. At least on Linux screen-session could scan  /proc/PID/environ and extract program specific vars. The access other user's processes it would be necessary to run as root.
0.60 has a nasty problem with process sorting by parent pid algorithm so shell->shell->shell->program (or longer) will be not properly recovered but it is fixed in git.

**Comment by vituko** [comment]
I agree, for me is also good enough. My typical use case is as an "IDE" with vim and for scripting languages and for that purpose, no complaints ;) I really hope that this project will continue growing and think that many people will be interested in it.
